### ISSUE TITLE
ttf corruption when requiring emoji

### ISSUE THREAD

**Issue by juanfal** [hidakatsuya/prawn-emoji#17]
Just after updating to last ruby 2.4 (brew), my projects using emoji are drawing the normal .ttf fonts numbers as circled emoji numbers.  Total disaster.  The only solution is banning emoji and rewrite it all

**Comment by aried3r** [comment]
We're facing the same issue using prawn 2.1.0 with Ruby 2.3 compiled from source on macOS 10.12.3 as well as Ubuntu 16.04.

**Comment by hidakatsuya** [comment]
OK, I'll confirm it.

**Comment by erdemgezer** [comment]
same here ;(

**Comment by hidakatsuya** [comment]
I have released 2.0.1. Thank you everyone.
https://github.com/hidakatsuya/prawn-emoji/releases/tag/2.0.1

**Comment by erdemgezer** [comment]
Great job!
Thanks @hidakatsuya

**Comment by juanfal** [comment]
Thanks, working nice!

-
