### ISSUE TITLE
zombies fail! missing new EmojiOne?

### ISSUE THREAD

**Issue by mattsly** [hidakatsuya/prawn-emoji#20]
zombie 🧟‍♂️ doesn't render when I test out a few common emoji issues even though it looks to be available in EmojiOne (found here https://www.emojicopy.com/)

Perhaps need to update to the latest EmojiOne 3.1.1 w/ some more images?

![image](https://user-images.githubusercontent.com/966935/39626698-14c796a6-4f71-11e8-9b8a-13e8c2e698b7.png)

**Comment by mattsly** [comment]
Related - can you clarify which version of EmojiOne this gem includes?

**Comment by hidakatsuya** [comment]
Yes, I will clarify the version used in this library. Perhaps this library includes version 2.

**Comment by hidakatsuya** [comment]
> clarify the version used in this gem

See https://github.com/hidakatsuya/prawn-emoji/commit/11e3cdb40ecba026cc7fe112ba2e4de388a31597

**Comment by hidakatsuya** [comment]
@mattsly 
Now v3.0 has been released. I belive that your problem will be resolved by v3.0.
https://github.com/hidakatsuya/prawn-emoji/blob/master/CHANGELOG.md#300

So, i closed this issue. Please feel free to reopen if you have any comment.
