### ISSUE TITLE
Leading not taken into account

### ISSUE THREAD

**Issue by xtian** [hidakatsuya/prawn-emoji#6]
When an emoji is rendered, the leading for the current text box isn't subtracted from the y coordinate for the image so it ends up rendering above the baseline for a line of text with leading set.

I looked into trying to fix this, but I wasn't able to find a way to access the current leading.

Example:
```ruby
@document.text '…', leading: 8
```
![screen shot 2016-02-01 at 2 16 11 pm](https://cloud.githubusercontent.com/assets/602654/12731526/9d041e38-c8ee-11e5-9a84-3e7205ba982a.png)

**Comment by hidakatsuya** [comment]
@xtian It seems to me that the leading is properly applied.

![screen shot 2016-03-20 at 03 00 54](https://cloud.githubusercontent.com/assets/739339/13900386/1e155cc0-ee48-11e5-859d-b98c4a410457.png)

However it seems that ends up rendering _a little_ above the baseline even if the leading is set 0. So i fix  like the below:

```diff
def draw_emoji(text, text_options)
  left_text, emoji_unicode, remaining_text = text.partition(@emoji_index.unicodes_regexp)

  return text if emoji_unicode.empty?

  emoji_image = Emoji::Image.new(emoji_unicode)

  emoji_x, emoji_y = text_options[:at]
  emoji_x += @document.width_of(left_text, text_options)
- emoji_y += @document.font_size
+ emoji_y += @document.font_size - 1

  draw_emoji_image emoji_image, at: [emoji_x, emoji_y], width: @document.font_size
  ...
 end
```

<img width="198" alt="screen shot 2016-03-20 at 03 14 08" src="https://cloud.githubusercontent.com/assets/739339/13900453/f5c59c60-ee49-11e5-842b-dc280d334e40.png">
<img width="191" alt="screen shot 2016-03-20 at 03 14 46" src="https://cloud.githubusercontent.com/assets/739339/13900452/f5c3de70-ee49-11e5-8a30-d2f410ed3f27.png">

**Comment by hidakatsuya** [comment]
@xtian Sorry, I've changed my mind. I won't fix, because it is the same position in comparison with the emoji in the original text.

<img width="127" alt="screen shot 2016-03-20 at 03 26 12" src="https://cloud.githubusercontent.com/assets/739339/13900545/338ebc1e-ee4c-11e5-976e-549eeab34c40.png">

**Comment by xtian** [comment]
@hidakatsuya Ok, I understand. Thank you for taking the time to investigate.
